vcpkg_check_linkage(ONLY_DYNAMIC_LIBRARY)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO shader-slang/slang-rhi
    REF 57b5dec033c90a4c8a29c0f50160003df18fb533
    SHA512 7fc626bfafe6146b3a51a8863f31599f089780067842f1f83a1e06be3509661fd14f33d0e1e3553d1a3e1ef9ef1a420cc91be3f3107c66e7f79b1c81b5c19f2f
    HEAD_REF main
    PATCHES
        fix_port.patch
)

vcpkg_check_features(OUT_FEATURE_OPTIONS FEATURE_OPTIONS
    FEATURES
        vulkan      SLANG_RHI_ENABLE_VULKAN
        d3d11       SLANG_RHI_ENABLE_D3D11
        d3d12       SLANG_RHI_ENABLE_D3D12
)

string(COMPARE EQUAL "${VCPKG_LIBRARY_LINKAGE}" "dynamic" SLANG_RHI_BUILD_SHARED)

vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS
        -DSLANG_RHI_BUILD_SHARED=${SLANG_RHI_BUILD_SHARED}
        -DSLANG_RHI_INSTALL=ON
        -DSLANG_RHI_BUILD_TESTS=OFF
        -DSLANG_RHI_BUILD_EXAMPLES=OFF
        -DSLANG_RHI_FETCH_SLANG=OFF
        ${FEATURE_OPTIONS}
        -DSLANG_RHI_ENABLE_CPU=ON
        -DSLANG_RHI_ENABLE_AGILITY_SDK=OFF
        -DSLANG_RHI_ENABLE_NVAPI=OFF
        -DSLANG_RHI_ENABLE_METAL=OFF
        -DSLANG_RHI_ENABLE_CUDA=OFF
        -DSLANG_RHI_ENABLE_OPTIX=OFF
        -DSLANG_RHI_ENABLE_WGPU=OFF
)

vcpkg_cmake_install()
vcpkg_copy_pdbs()
vcpkg_cmake_config_fixup(PACKAGE_NAME "slang-rhi")

vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/LICENSE")

file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include")
